import React from 'react';

export default function CookiePolicy() {
  return (
    <div style={{ padding: '40px', maxWidth: '800px', margin: '0 auto', lineHeight: '1.6', color: '#fff' }}>
      <h1>Cookie Policy</h1>
      <p>Last updated: May 2026</p>
      
      <h2>1. Introduction</h2>
      <p>This Cookie Policy explains how we use cookies and similar technologies. This interface is designed to be privacy-respecting and transparent about data practices.</p>
      
      <h2>2. No Personal Tracking</h2>
      <p>This interface does not use third-party advertising cookies or tracking pixels. Google Analytics and Vercel Analytics have been removed to ensure user anonymity.</p>
      
      <h2>3. Strictly Necessary Cookies</h2>
      <p>Only essential cookies strictly necessary for the technical operation of this decentralized interface are used, such as wallet connection state and network preference.</p>
      
      <h2>4. Protocol Revenue and Transparency</h2>
      <p>All fees generated by the protocol are routed to the treasury wallet. No individual user financial data is tracked beyond what is publicly available on the blockchain.</p>
      
      <div style={{ marginTop: '40px', borderTop: '1px solid #333', paddingTop: '20px' }}>
        <p><a href="/" style={{ color: '#0070f3' }}>← Return to Home</a></p>
      </div>
    </div>
  );
}
