import React from 'react';

export default function CookiePolicy() {
  return (
    <div style={{ padding: '40px', maxWidth: '800px', margin: '0 auto', lineHeight: '1.6', color: '#fff' }}>
      <h1>Cookie Policy</h1>
      <p>Last updated: May 2026</p>
      
      <h2>1. Introduction</h2>
      <p>This Cookie Policy explains how we use cookies and similar technologies. We are committed to protecting your privacy and being transparent about our data practices.</p>
      
      <h2>2. No Personal Tracking</h2>
      <p>Our platform is designed to be privacy-respecting. We do not use third-party advertising cookies or tracking pixels that identify you personally. We have removed Google Analytics and Vercel Analytics to ensure your anonymity.</p>
      
      <h2>3. Strictly Necessary Cookies</h2>
      <p>We only use essential cookies that are strictly necessary for the technical operation of the decentralized interface, such as remembering your wallet connection state and network preference.</p>
      
      <h2>4. Protocol Revenue and Transparency</h2>
      <p>All fees generated by the protocol are routed to the treasury wallet. We do not track individual user financial data beyond what is publicly available on the blockchain.</p>
      
      <div style={{ marginTop: '40px', borderTop: '1px solid #333', paddingTop: '20px' }}>
        <p><a href="/" style={{ color: '#0070f3' }}>← Return to Home</a></p>
      </div>
    </div>
  );
}
